ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - name: Start Redis
    init: docker-compose up -d
    command: gp sync-done finished
    openMode: split-left
  - name: Start Flask Application
      export FLASK_APP=flaskr
      export FLASK_ENV=development
    init: |
      pip install -e .
    command: flask run
    openMode: split-right

vscode:
  extensions:
    - ms-python.python
